//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easily create a lock screen as in Windows 10.
        ///Use your own pictures and see how your lock screen changes every half hour.
        ///There are many options available for this.
        ///You&apos;ll be amazed!
        ///
        ///- Supports all display formats
        ///- Created every 30 minutes a new lock screen from 3 different image formats
        ///- Changing background pictures
        ///- Changing user pictures
        ///- Advanced user information
        ///- Adjustable colors
        ///- Use of infinitely many images
        ///- Endless possibilities.
        /// </summary>
        public static string AAA0 {
            get {
                return ResourceManager.GetString("AAA0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Screen.
        /// </summary>
        public static string AAA1 {
            get {
                return ResourceManager.GetString("AAA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Image.
        /// </summary>
        public static string AAA2 {
            get {
                return ResourceManager.GetString("AAA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper.
        /// </summary>
        public static string AAA3 {
            get {
                return ResourceManager.GetString("AAA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display picture.
        /// </summary>
        public static string AAA4 {
            get {
                return ResourceManager.GetString("AAA4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop picture.
        /// </summary>
        public static string AAA5 {
            get {
                return ResourceManager.GetString("AAA5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to foto photo picture image graphics design.
        /// </summary>
        public static string AAA6 {
            get {
                return ResourceManager.GetString("AAA6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.0 Lock Screen.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial version.
        /// </summary>
        public static string X_001_trialVersion {
            get {
                return ResourceManager.GetString("X_001_trialVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string X002_about {
            get {
                return ResourceManager.GetString("X002_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent color.
        /// </summary>
        public static string X002_accentColor {
            get {
                return ResourceManager.GetString("X002_accentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string X002_add {
            get {
                return ResourceManager.GetString("X002_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select pictures to the add.
        /// </summary>
        public static string X002_addNoImages {
            get {
                return ResourceManager.GetString("X002_addNoImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add pictures.
        /// </summary>
        public static string X002_addPictures {
            get {
                return ResourceManager.GetString("X002_addPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all pictures.
        /// </summary>
        public static string X002_allPictures {
            get {
                return ResourceManager.GetString("X002_allPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        public static string X002_backgroundColor {
            get {
                return ResourceManager.GetString("X002_backgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock screen changer.
        /// </summary>
        public static string X002_backgroundTask {
            get {
                return ResourceManager.GetString("X002_backgroundTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy this app.
        /// </summary>
        public static string X002_buy {
            get {
                return ResourceManager.GetString("X002_buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string X002_cancel {
            get {
                return ResourceManager.GetString("X002_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string X002_changeLanguage {
            get {
                return ResourceManager.GetString("X002_changeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here.
        /// </summary>
        public static string X002_clickHere {
            get {
                return ResourceManager.GetString("X002_clickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already used colors.
        /// </summary>
        public static string X002_colorsUsed {
            get {
                return ResourceManager.GetString("X002_colorsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string X002_contact {
            get {
                return ResourceManager.GetString("X002_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message to xtrose.
        /// </summary>
        public static string X002_contactMsg {
            get {
                return ResourceManager.GetString("X002_contactMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy.
        /// </summary>
        public static string X002_copy {
            get {
                return ResourceManager.GetString("X002_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        public static string X002_createNew {
            get {
                return ResourceManager.GetString("X002_createNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cut.
        /// </summary>
        public static string X002_cut {
            get {
                return ResourceManager.GetString("X002_cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add selected pictures to previously.
        /// </summary>
        public static string X002_cutSelected {
            get {
                return ResourceManager.GetString("X002_cutSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string X002_day {
            get {
                return ResourceManager.GetString("X002_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string X002_days {
            get {
                return ResourceManager.GetString("X002_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string X002_delete {
            get {
                return ResourceManager.GetString("X002_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string X002_deleteLockScreen {
            get {
                return ResourceManager.GetString("X002_deleteLockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete lock screen with all pictures and settings.
        /// </summary>
        public static string X002_deleteMessage {
            get {
                return ResourceManager.GetString("X002_deleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use.
        /// </summary>
        public static string X002_doNotUse {
            get {
                return ResourceManager.GetString("X002_doNotUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR! Name already in use or invalid characters!.
        /// </summary>
        public static string X002_errorName {
            get {
                return ResourceManager.GetString("X002_errorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background agents for this application have been disabled by the user.
        /// </summary>
        public static string X002_exError {
            get {
                return ResourceManager.GetString("X002_exError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font color.
        /// </summary>
        public static string X002_fontColor {
            get {
                return ResourceManager.GetString("X002_fontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground color.
        /// </summary>
        public static string X002_foregroundColor {
            get {
                return ResourceManager.GetString("X002_foregroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame color.
        /// </summary>
        public static string X002_frameColor {
            get {
                return ResourceManager.GetString("X002_frameColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame size.
        /// </summary>
        public static string X002_frameSize {
            get {
                return ResourceManager.GetString("X002_frameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string X002_generateNew {
            get {
                return ResourceManager.GetString("X002_generateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string X002_headerBackground {
            get {
                return ResourceManager.GetString("X002_headerBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture frame.
        /// </summary>
        public static string X002_headerFrame {
            get {
                return ResourceManager.GetString("X002_headerFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string X002_headerPictures {
            get {
                return ResourceManager.GetString("X002_headerPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string X002_hour {
            get {
                return ResourceManager.GetString("X002_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string X002_hours {
            get {
                return ResourceManager.GetString("X002_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info color.
        /// </summary>
        public static string X002_infoColor {
            get {
                return ResourceManager.GetString("X002_infoColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information background.
        /// </summary>
        public static string X002_informationBackground {
            get {
                return ResourceManager.GetString("X002_informationBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info size.
        /// </summary>
        public static string X002_infoSize {
            get {
                return ResourceManager.GetString("X002_infoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info transparency.
        /// </summary>
        public static string X002_infoTransparency {
            get {
                return ResourceManager.GetString("X002_infoTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape format.
        /// </summary>
        public static string X002_landscapeFormat {
            get {
                return ResourceManager.GetString("X002_landscapeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string X002_language {
            get {
                return ResourceManager.GetString("X002_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string X002_left {
            get {
                return ResourceManager.GetString("X002_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading....
        /// </summary>
        public static string X002_loading {
            get {
                return ResourceManager.GetString("X002_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You said no, so I can&apos;t update your background.
        /// </summary>
        public static string X002_lockHelperInfo {
            get {
                return ResourceManager.GetString("X002_lockHelperInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Screen.
        /// </summary>
        public static string X002_lockScreen {
            get {
                return ResourceManager.GetString("X002_lockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock screen can no longer be changed.
        /// </summary>
        public static string X002_lockScreenOff {
            get {
                return ResourceManager.GetString("X002_lockScreenOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Screens.
        /// </summary>
        public static string X002_lockScreens {
            get {
                return ResourceManager.GetString("X002_lockScreens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        public static string X002_lpBackgroundColor {
            get {
                return ResourceManager.GetString("X002_lpBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background pictures.
        /// </summary>
        public static string X002_lpBackgroundPictures {
            get {
                return ResourceManager.GetString("X002_lpBackgroundPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string X002_maximum {
            get {
                return ResourceManager.GetString("X002_maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        public static string X002_minimum {
            get {
                return ResourceManager.GetString("X002_minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        public static string X002_minute {
            get {
                return ResourceManager.GetString("X002_minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string X002_minutes {
            get {
                return ResourceManager.GetString("X002_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string X002_msgCopy {
            get {
                return ResourceManager.GetString("X002_msgCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string X002_msgDelete {
            get {
                return ResourceManager.GetString("X002_msgDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string X002_next {
            get {
                return ResourceManager.GetString("X002_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string X002_no {
            get {
                return ResourceManager.GetString("X002_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No other lock screens.
        /// </summary>
        public static string X002_noLockScreens {
            get {
                return ResourceManager.GetString("X002_noLockScreens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lock screens available.
        /// </summary>
        public static string X002_noLockScreens1 {
            get {
                return ResourceManager.GetString("X002_noLockScreens1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to create your first lock screen.
        /// </summary>
        public static string X002_noLockScreens2 {
            get {
                return ResourceManager.GetString("X002_noLockScreens2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First create a lock screen.
        /// </summary>
        public static string X002_noLockScreens3 {
            get {
                return ResourceManager.GetString("X002_noLockScreens3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh not possible.
        /// </summary>
        public static string X002_noLockScreens5 {
            get {
                return ResourceManager.GetString("X002_noLockScreens5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check settings.
        /// </summary>
        public static string X002_noLockScreens6 {
            get {
                return ResourceManager.GetString("X002_noLockScreens6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pictures available.
        /// </summary>
        public static string X002_noPictures {
            get {
                return ResourceManager.GetString("X002_noPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least one picture.
        /// </summary>
        public static string X002_noPictures2 {
            get {
                return ResourceManager.GetString("X002_noPictures2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pictures available.
        /// </summary>
        public static string X002_noPictures5 {
            get {
                return ResourceManager.GetString("X002_noPictures5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to add pictures.
        /// </summary>
        public static string X002_noPictures6 {
            get {
                return ResourceManager.GetString("X002_noPictures6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create lock screen.
        ///There must be at least one picture..
        /// </summary>
        public static string X002_noPicturesAvailable {
            get {
                return ResourceManager.GetString("X002_noPicturesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing selected.
        /// </summary>
        public static string X002_nothingSelected {
            get {
                return ResourceManager.GetString("X002_nothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set.
        /// </summary>
        public static string X002_notSet {
            get {
                return ResourceManager.GetString("X002_notSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only available in the full version.
        /// </summary>
        public static string X002_onlyFullVersion {
            get {
                return ResourceManager.GetString("X002_onlyFullVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string X002_overview {
            get {
                return ResourceManager.GetString("X002_overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string X002_picture {
            get {
                return ResourceManager.GetString("X002_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string X002_pictures {
            get {
                return ResourceManager.GetString("X002_pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures transparency.
        /// </summary>
        public static string X002_pictureTransparency {
            get {
                return ResourceManager.GetString("X002_pictureTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait format.
        /// </summary>
        public static string X002_portraitFormat {
            get {
                return ResourceManager.GetString("X002_portraitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string X002_preview {
            get {
                return ResourceManager.GetString("X002_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous.
        /// </summary>
        public static string X002_previous {
            get {
                return ResourceManager.GetString("X002_previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for purchasing this app.
        /// </summary>
        public static string X002_purchaseNote {
            get {
                return ResourceManager.GetString("X002_purchaseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string X002_quality {
            get {
                return ResourceManager.GetString("X002_quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this app.
        /// </summary>
        public static string X002_rate {
            get {
                return ResourceManager.GetString("X002_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string X002_rateBtnBack {
            get {
                return ResourceManager.GetString("X002_rateBtnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message to xtrose.
        /// </summary>
        public static string X002_rateBtnMsg {
            get {
                return ResourceManager.GetString("X002_rateBtnMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not now.
        /// </summary>
        public static string X002_rateBtnNotNow {
            get {
                return ResourceManager.GetString("X002_rateBtnNotNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string X002_rateBtnRate {
            get {
                return ResourceManager.GetString("X002_rateBtnRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review this app 5 stars.
        /// </summary>
        public static string X002_rateHeader {
            get {
                return ResourceManager.GetString("X002_rateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application seems to appeal to you.
        ///To program apps is time consuming and difficult.
        ///A good review can help us to spread it further.
        ///
        ///Thank you very much.
        /// </summary>
        public static string X002_rateText1 {
            get {
                return ResourceManager.GetString("X002_rateText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t want to write a review.
        ///
        ///Please write a message us if you have any suggestions or problems..
        /// </summary>
        public static string X002_rateText2 {
            get {
                return ResourceManager.GetString("X002_rateText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        public static string X002_right {
            get {
                return ResourceManager.GetString("X002_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rotate left.
        /// </summary>
        public static string X002_rotateLeft {
            get {
                return ResourceManager.GetString("X002_rotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rotate right.
        /// </summary>
        public static string X002_rotateRight {
            get {
                return ResourceManager.GetString("X002_rotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string X002_save {
            get {
                return ResourceManager.GetString("X002_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and share.
        /// </summary>
        public static string X002_saveAndShare {
            get {
                return ResourceManager.GetString("X002_saveAndShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture was saved.
        /// </summary>
        public static string X002_saved {
            get {
                return ResourceManager.GetString("X002_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saved pictures.
        /// </summary>
        public static string X002_savedPictures {
            get {
                return ResourceManager.GetString("X002_savedPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select all.
        /// </summary>
        public static string X002_selectAll {
            get {
                return ResourceManager.GetString("X002_selectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string X002_settings {
            get {
                return ResourceManager.GetString("X002_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string X002_size {
            get {
                return ResourceManager.GetString("X002_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square format.
        /// </summary>
        public static string X002_squareFormat {
            get {
                return ResourceManager.GetString("X002_squareFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System colors.
        /// </summary>
        public static string X002_systemColors {
            get {
                return ResourceManager.GetString("X002_systemColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change lock screen enabled.
        /// </summary>
        public static string X002_taskInfo {
            get {
                return ResourceManager.GetString("X002_taskInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string X002_text {
            get {
                return ResourceManager.GetString("X002_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you very much.
        /// </summary>
        public static string X002_thankYou {
            get {
                return ResourceManager.GetString("X002_thankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency.
        /// </summary>
        public static string X002_transparency {
            get {
                return ResourceManager.GetString("X002_transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial period expired.
        /// </summary>
        public static string X002_trialExpired {
            get {
                return ResourceManager.GetString("X002_trialExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unselect all.
        /// </summary>
        public static string X002_unselectAll {
            get {
                return ResourceManager.GetString("X002_unselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string X002_use {
            get {
                return ResourceManager.GetString("X002_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User informations.
        /// </summary>
        public static string X002_userInformations {
            get {
                return ResourceManager.GetString("X002_userInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User pictures.
        /// </summary>
        public static string X002_userPictures {
            get {
                return ResourceManager.GetString("X002_userPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical alignment.
        /// </summary>
        public static string X002_verticalAlignment {
            get {
                return ResourceManager.GetString("X002_verticalAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string X002_warning {
            get {
                return ResourceManager.GetString("X002_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string X002_yes {
            get {
                return ResourceManager.GetString("X002_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look.
        /// </summary>
        public static string X003_look {
            get {
                return ResourceManager.GetString("X003_look", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string X003_random {
            get {
                return ResourceManager.GetString("X003_random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random from all.
        /// </summary>
        public static string X003_randomAll {
            get {
                return ResourceManager.GetString("X003_randomAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string X003_required {
            get {
                return ResourceManager.GetString("X003_required", resourceCulture);
            }
        }
    }
}
